### ISSUE TITLE
Compilation issues with InterPSS libs

### ISSUE THREAD

**Issue by thuang** [thuang/InterPSS_3phase#4]
@jinjingfarm 

The codes are under https://github.com/thuang/InterPSS_3phase/tree/master_lib

The original master version (depends on Ipss source codes) has no compilation issues,  For some development, I need to provide the codes to my colleagues, so I switched to the InterPSS libs , some compilation issues still remained, even with the latest jars that you created

![image](https://user-images.githubusercontent.com/529196/73388403-016a8e00-4287-11ea-930a-b1c0cefaf451.png)

![image](https://user-images.githubusercontent.com/529196/73388437-10e9d700-4287-11ea-9dd6-28b50dc8e21c.png)

**Comment by jinjingfarm** [comment]
The issue should have been resolved with the commit https://github.com/InterPSS-Project/ipss-common/commit/2c6490efbf5568710393afd79cdb148c4ae6ee8a

**Comment by jinjingfarm** [comment]
Starting from this point, the ipss.core.jar and ipss.core.impl.jar have been combined into one jar file ipss.core.jar.

**Comment by thuang** [comment]
The issue has been fixed. Thanks @jinjingfarm
